name: Testing a custom gh action.

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  test:
    name: "test job"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"
      - uses: nouailibh/scripts-runner
        name: scripts-runner
        id: scr
        with:
          scripts-folder: "scripts"
      - name: Get the output
        run: echo "Result -> ${{steps.scr.outputs}}"
